require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhotoJobsController do

  # This should return the minimal set of attributes required to create a valid
  # PhotoJob. As you add validations to PhotoJob, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  include Devise::TestHelpers

  before do
    @user = stub_model(User)
    @album = stub_model(Album, :user => @user)
    @scan = stub_model(Scan, :album => @album)
    sign_in @user
  end

  describe "GET index" do
    it "assigns all photo_jobs as @photo_jobs" do
      photo_job = PhotoJob.create! valid_attributes
      get :index, :scan_id => @scan
      assigns(:photo_jobs).should eq([photo_job])
    end
  end

  describe "GET show" do
    it "assigns the requested photo_job as @photo_job" do
      photo_job = PhotoJob.create! valid_attributes
      get :show, :id => photo_job.id.to_s
      assigns(:photo_job).should eq(photo_job)
    end
  end

  describe "GET new" do
    it "assigns a new photo_job as @photo_job" do
      get :new, :scan_id => @scan
      assigns(:photo_job).should be_a_new(PhotoJob)
    end
  end

  describe "GET edit" do
    it "assigns the requested photo_job as @photo_job" do
      photo_job = PhotoJob.create! valid_attributes
      get :edit, :id => photo_job.id.to_s
      assigns(:photo_job).should eq(photo_job)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PhotoJob" do
        expect {
          post :create, :photo_job => valid_attributes, :scan_id => @scan
        }.to change(PhotoJob, :count).by(1)
      end

      it "assigns a newly created photo_job as @photo_job" do
        post :create, :photo_job => valid_attributes, :scan_id => @scan
        assigns(:photo_job).should be_a(PhotoJob)
        assigns(:photo_job).should be_persisted
      end

      it "redirects to the created photo_job" do
        post :create, :photo_job => valid_attributes, :scan_id => @scan
        response.should redirect_to(PhotoJob.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved photo_job as @photo_job" do
        # Trigger the behavior that occurs when invalid params are submitted
        PhotoJob.any_instance.stubs(:save).returns(false)
        post :create, :photo_job => {}, :scan_id => @scan
        assigns(:photo_job).should be_a_new(PhotoJob)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PhotoJob.any_instance.stubs(:save).returns(false)
        post :create, :photo_job => {}, :scan_id => @scan
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested photo_job" do
        photo_job = PhotoJob.create! valid_attributes
        # Assuming there are no other photo_jobs in the database, this
        # specifies that the PhotoJob created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PhotoJob.any_instance.expects(:update_attributes).with({'these' => 'params'})
        put :update, :id => photo_job.id, :photo_job => {'these' => 'params'}
      end

      it "assigns the requested photo_job as @photo_job" do
        photo_job = PhotoJob.create! valid_attributes
        put :update, :id => photo_job.id, :photo_job => valid_attributes
        assigns(:photo_job).should eq(photo_job)
      end

      it "redirects to the photo_job" do
        photo_job = PhotoJob.create! valid_attributes
        put :update, :id => photo_job.id, :photo_job => valid_attributes
        response.should redirect_to(photo_job)
      end
    end

    describe "with invalid params" do
      it "assigns the photo_job as @photo_job" do
        photo_job = PhotoJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PhotoJob.any_instance.stubs(:save).returns(false)
        put :update, :id => photo_job.id.to_s, :photo_job => {}
        assigns(:photo_job).should eq(photo_job)
      end

      it "re-renders the 'edit' template" do
        photo_job = PhotoJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PhotoJob.any_instance.stubs(:save).returns(false)
        put :update, :id => photo_job.id.to_s, :photo_job => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested photo_job" do
      photo_job = PhotoJob.create! valid_attributes
      expect {
        delete :destroy, :id => photo_job.id.to_s
      }.to change(PhotoJob, :count).by(-1)
    end

    it "redirects to the photo_jobs list" do
      photo_job = PhotoJob.create! valid_attributes
      delete :destroy, :id => photo_job.id.to_s
      response.should redirect_to(scan_photo_jobs_path(@scan))
    end
  end

end
